config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'children#index'
  resources :children do
    resources :breasts, only: [:new, :create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle.rb
class Bottle < ApplicationRecord
  belongs_to :child
end

app/models/breast.rb
class Breast < ApplicationRecord
  belongs_to :child
  before_save :breast_time_save
  default_scope -> { order(start_time: :asc) }

  with_options presence: true do
    validates :side
    validates :start_time
    validates :end_time, numericality: { greater_than: :start_time, message: 'must be greater than start time.' }
  end

  def breast_time_save
    start_time = read_attribute(:start_time)
    end_time = read_attribute(:end_time)
    breast_time = end_time - start_time
    write_attribute(:breast_time, breast_time)
  end
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  has_many :breasts, dependent: :destroy
  has_many :bottles, dependent: :destroy
  has_many :pees, dependent: :destroy
  has_many :poops, dependent: :destroy

  validates :name, presence: true
  validates :birth_day, presence: true
end

app/models/pee.rb
class Pee < ApplicationRecord
  belongs_to :child
end

app/models/poop.rb
class Poop < ApplicationRecord
  belongs_to :child
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :children, dependent: :destroy

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze

  validates :name, presence: true
  validates :password, format: { with: PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_parmitted_parameters, if: :devise_controller?

  private

  def configure_parmitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['B_BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/breasts_controller.rb
class BreastsController < ApplicationController
  before_action :set_breast, only: [:edit, :update]

  def new
    @breast = Breast.new
    @child = Child.find(params[:child_id])
  end

  def create
    @breast = Breast.new(breast_params)
    if @breast.valid?
      @breast.save
      redirect_to child_path(params[:child_id])
    else
      render :new
    end
  end

  def edit
  end

  def update
    @breast.update(breast_params)
    if @breast.valid?
      @breast.save
      redirect_to child_path(params[:child_id])
    else
      render :edit
    end
  end

  private

  def breast_params
    params.require(:breast).permit(:side, :breast_time, :start_time, :end_time).merge(child_id: params[:child_id])
  end

  def set_breast
    @breast = Breast.find(params[:id])
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update]
  before_action :set_children, only: [:index, :show]

  def index
  end

  def new
    @child = Child.new
  end

  def create
    @child = Child.new(child_params)
    if @child.valid?
      @child.save
      redirect_to child_path(@child)
    else
      render :new
    end
  end

  def show
    set_times
    set_items
  end

  def edit
  end

  def update
    @child.update(child_params)
    if @child.valid?
      @child.save
      redirect_to child_path(@child)
    else
      render :edit
    end
  end

  private

  def child_params
    params.require(:child).permit(:name, :birth_day).merge(user_id: current_user.id)
  end

  def set_child
    @child = Child.find(params[:id])
  end

  def set_children
    @children = current_user.children if user_signed_in?
  end

  def set_times
    @t = Time.current
    @times = []
    t = Time.current
    i = 7
    11.times do |_j|
      @times << t.ago(i.hours)
      i -= 1
    end
  end

  def set_items
    @breasts = @child.breasts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breasts_helper.rb
module BreastsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/breasts/edit.html.erb
<%= render "shared/second_header" %>

<%= form_with model: @breast, url: child_breast_path(params[:child_id]), class: "breast-form", local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      授乳記録編集
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-time">
    <p>飲み始め時間</p>
    <%= f.datetime_select :start_time, default: @breast.start_time, use_month_numbers: true %>
  </div>
  <div class="form-time">
    <p>飲み終わり時間</p>
    <%= f.datetime_select :end_time, default: @breast.end_time, use_month_numbers: true %>
  </div>

  <div class="btn-wrap">
      <label class="btn-box">
        <%= f.radio_button :side, 'breast_left.png', class: "radio-btn" %>
        <%= image_tag 'breast_left.png', class: "btn-icon" %>
      </label>
      <label class="btn-box">
        <%= f.radio_button :side, 'breast_right.png', class: "radio-btn" %>
        <%= image_tag 'breast_right.png', class: "btn-icon" %>
      </label>
  </div>
  <%= f.submit '保存', class: "submit" %>
  <%= link_to "戻る", child_path(params[:child_id]), class: "back-btn" %>
</div>
<% end %>


<%= render "shared/second_footer" %>

app/views/breasts/new.html.erb
<%= render "shared/second_header" %>

<%= form_with model: @breast, url: child_breasts_path(params[:child_id]), class: "breast-form", local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      授乳記録
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-time">
    <p>飲み始め時間</p>
    <%= f.datetime_select :start_time, default: Time.current - 15.minute, use_month_numbers: true %>
  </div>
  <div class="form-time">
    <p>飲み終わり時間</p>
    <%= f.datetime_select :end_time, default: Time.current, use_month_numbers: true %>
  </div>

  <div class="btn-wrap">
      <label class="btn-box">
        <%= f.radio_button :side, 'breast_left.png', class: "radio-btn" %>
        <%= image_tag 'breast_left.png', class: "btn-icon" %>
      </label>
      <label class="btn-box">
        <%= f.radio_button :side, 'breast_right.png', class: "radio-btn" %>
        <%= image_tag 'breast_right.png', class: "btn-icon" %>
      </label>
  </div>
  <%= f.submit '保存', class: "submit" %>
  <%= link_to "戻る", child_path(params[:child_id]), class: "back-btn" %>
</div>
<% end %>



<%= render "shared/second_footer" %>

app/views/children/edit.html.erb
<%= render "shared/second_header" %>
<div class="header-bk">
</div>

<%= form_with model: @child, url: child_path(@child.id), class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      お子様情報編集
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"input-default", id:"name", maxlength:"40", autofocus: true %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_day,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: (Time.now.year),
                    end_year: (Time.now.year - 3),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  <div class='register-btn'>
    <%= f.submit "登録" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

<%= render "shared/second_footer" %>

app/views/children/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="main-container">
  <% unless user_signed_in? %>
    <div class="sample-wrap">
      <p>サンプル画像</p>
      <%= image_tag 'sample.png' , class: "sample" %>
    </div>
  <% end %>
  <% if user_signed_in? %>
  <div class='main-link'>
    <%= link_to 'お子様情報の登録', new_child_path, class: "new-child" %>
    <div class="edit-child">お子様情報の編集
      <ul class="edit-child-link">
        <% @children.each do |child| %>
          <li class="edit-list">
            <%= link_to "#{child.name}", edit_child_path(child.id), class: 'child-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  </div>
</div>

<%= render "shared/second_footer" %>

app/views/children/new.html.erb
<%= render "shared/second_header" %>

<%= form_with model: @child, url: children_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      お子様情報入力
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"input-default", id:"name", maxlength:"40", autofocus: true %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_day,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: (Time.now.year),
                    end_year: (Time.now.year - 3),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  <div class='register-btn'>
    <%= f.submit "登録" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

<%= render "shared/second_footer" %>

app/views/children/show.html.erb
<%= render "shared/header" %>

<div class='child-main'>
  <div class='child-container'>
    <hr>
    <% @times.each do |time| %>
      <div class="time-line">
        <% if time.hour == Time.current.hour %>
          <div class="time now">
        <% else %>
          <div class="time">
        <% end %>
          <%= time.hour %>
        </div>

        <div class="time-line-bk">
        </div>

        <% @breasts.each do |breast| %>
          <% if time.strftime("%F/%H") == breast.start_time.strftime("%F/%H") %>
            <div class="item-wrap">
              <div class="icon-wrap">
                <%= breast.start_time.strftime("%H:%M") %>
                <%= link_to edit_child_breast_path(@child.id, breast.id), class: "edit-breast" do %>
                  <%= image_tag breast.side, class: "item-icon" %>
                <% end %>
              </div>
              <div class="item">
                <%= "#{breast.breast_time / 60}分 "%>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <hr>
      <% if time.hour == 23 %>
        <div class="date-line">
          <hr class="line">
          <p class="day">
            <%= "#{time.month}/#{time.day + 1}" %>
          </p>
          <hr class="line">
        </div>
        <hr>
      <% end %>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabyJournal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel = "stylesheet" type = "text / css" href = "http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css" >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <%= link_to "育児日記", root_path, class: "footer-logo"%>
  <p>©︎ BabyJournal28292</p>
</footer>
<div class="btn-list">
<%= link_to new_child_breast_path(@child.id), class: "link-icon" do %>
  <%= image_tag 'breast.png', class: "icon" %>
<% end %>

<%= image_tag 'timer.png', class: "icon" %>
<%= image_tag 'bottole.png', class: "icon" %>
<%= image_tag 'pee.png', class: "icon" %>
<%= image_tag 'poop.png', class: "icon" %>
</div>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-bar">
    <%= link_to root_path do %>
      <h1 class="title-logo">育児日記</h1>
    <% end %>
    <% if user_signed_in? %>
      <div class="user-info">
        <div class="child-name" id="lists">
          <% if @child %>
            <%= @child.name %>
          <% else %>
            記録をつける
          <% end %>
          <ul class="show-lists hidden" id="pull-down">
            <% @children.each do |child| %>
              <li class="pull-down-list">
                <%= link_to "#{child.name}", child_path(child.id), class: 'child-link' %>
              </li>
            <% end %>
          </ul>
        </div>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %>
      </div>
    <% else %>
      <div class="user-info">
        <%= link_to "ログイン", new_user_session_path, class: "login" %>
        <%= link_to "新規登録", new_user_registration_path, class: "sign-up" %>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_second_footer.html.erb
<footer class="second-footer">
  <%= link_to "育児日記", root_path, class: "footer-logo"%>
  <p>©︎ BabyJournal28292</p>
</footer>

app/views/shared/_second_header.html.erb
<header class="header">
  <div class="header-bar">
    <%= link_to root_path do %>
      <h1 class="title-logo">育児日記</h1>
    <% end %>
  </div>
</header>
<div class="header-bk">
</div>